apiVersion: v1
data:
  myconfig.js: |
    {
      "id": "HEPop101",
      "socket": "http",
      "port": 8090,
      "address": "0.0.0.0",
      "queue": {
        "timeout": 2000,
        "maxSize": 1000,
        "useInterval": true
      },
      "dbName": "homer_data",
      "tableName": "hep",
      "db": {
        "rawSize": 8090,
        "elastic": {
          "target": "https://vpc-evercast-development-e2rczi5elp6b5y72jzolxpkf24.us-east-1.es.amazonaws.com:443",
          "max_bulk_qtty": 10,
          "max_request_num": 20,
          "index": "homer"
        }
      },
      "metrics": {
            "influx":{
              "period": 30000,
              "expire": 300000,
              "dbName": "homer",
              "hostname": "telegraf:8094"
            }
      },
      "debug": false
    }
kind: ConfigMap
metadata:
  name: heplify-server-config
